### ISSUE TITLE
Print files generated / by the generator as a file list

### ISSUE THREAD

**Issue by zambrovski** [toolisticon/kotlin-code-generation#41]
### Scenario

* Description of your use case: As a developer I want to have way to navigate to generated files.

### Current Behaviour

Not printed

### Wanted Behaviour

Simple switch to print the generated file list (navigatable)

### Possible Workarounds

```kotlin

    val result = KotlinCodeGenerationTest.compile(
      KotlinCompilationCommand(
        fileSpecs = files
      )
    )

    result.result.messages.lines()
      .filter { line -> line.endsWith(".kt") }
      .distinct()
      .forEach { message -> println("file://$message") }

```

**Comment by jangalinski** [comment]
call `result.toString()` to see the generated files
